-- Datos generados por scripts/migrar.js — no editar a mano.
-- Ejecutar DESPUES de 01-schema.sql

begin;

-- ==================================================================
-- SUCURSALES
-- ==================================================================
insert into sucursales (codigo, nombre, ciudad, activa, alias) values
  ('GDL', 'Guadalajara — CEDIS Amapola', 'Guadalajara', true, array['cedis','amapola','gdl','p1c','corporativo']),
  ('HMO', 'Hermosillo', 'Hermosillo', true, array['hermosillo','hmo']),
  ('CUU', 'Chihuahua', 'Chihuahua', true, array['chihuahua','cuu']),
  ('CDJ', 'Ciudad Juárez', 'Ciudad Juárez', true, array['ciudad juarez','cd juarez','juarez','cd j','cdju','cd. juarez']),
  ('LEO', 'León', 'León', true, array['leon','león']),
  ('AGS', 'Aguascalientes', 'Aguascalientes', true, array['aguascalientes','ags']),
  ('MTY', 'Monterrey (cerrada jul-2026)', 'Monterrey', false, array['monterrey','mty']);

-- ==================================================================
-- PRESUPUESTO 2026
-- ==================================================================
insert into presupuestos (sucursal_id, anio, monto_solicitado, monto_aprobado, notas)
select s.id, v.anio, v.solicitado, v.aprobado, v.notas from (values
  ('GDL', 2026, 1401230::numeric, 1100000::numeric, null),
  ('HMO', 2026, 800000::numeric, 600000::numeric, null),
  ('CUU', 2026, 800000::numeric, 600000::numeric, null),
  ('MTY', 2026, 400000::numeric, null::numeric, 'Sucursal cerrada en julio 2026. Sin presupuesto aprobado.'),
  ('CDJ', 2026, 300000::numeric, 350000::numeric, null),
  ('LEO', 2026, 200000::numeric, 220000::numeric, null),
  ('AGS', 2026, 270000::numeric, null::numeric, 'SIN PRESUPUESTO APROBADO pese a tener gasto ejercido. Revisar con direccion.')
) as v(codigo, anio, solicitado, aprobado, notas)
join sucursales s on s.codigo = v.codigo;

-- ==================================================================
-- CATEGORIAS
-- ==================================================================
insert into categorias (nombre, orden) values
  ('Electrico', 1),
  ('Iluminacion', 2),
  ('Estructural', 3),
  ('Equipos Electricos', 4),
  ('Aire Acondicionado', 5),
  ('Mobiliario', 6),
  ('Hidraulico', 7),
  ('Neumatico', 8),
  ('Desagues', 9),
  ('Seguridad', 10),
  ('Limpieza', 11),
  ('Fumigacion', 12),
  ('Vehiculos', 13);

-- ==================================================================
-- GASTOS (detalle enero–junio 2026)
-- ==================================================================

-- ==================================================================
-- PROVEEDORES
-- ==================================================================
insert into proveedores (nombre, servicio, es_fijo) values
  ('CONSTRUCTORA HESSE SAJONIA', null, false),
  ('GRUPO BRAGA OPORTO', null, false),
  ('REFACCIONARIA FERRETERA SA DE CV', null, false),
  ('ADHESELLA Y COMPLEMENTOS', null, false),
  ('GAS EL SOBRANTE', null, false),
  ('JOSE GUADALUPE RAMIREZ AGUAYO', null, false),
  ('CONSTRUCCIONES Y REMODELACIONES SAN', null, false),
  ('DISTRIBUIDORA PINTA FAMM S.A. DE C.V.', null, false),
  ('MARBUS MKT', null, false),
  ('LUIS ALBERTO ARROYO CHAVEZ', null, false),
  ('INGENIERIA Y MOVILIDAD URBANA IMU SA DE CV', null, false),
  ('JORGE LUIS REYES ADRIANO', null, false),
  ('DAVID ALMENDRA GUZMAN', null, false),
  ('JESUS BALDERAS ROJAS', null, false),
  ('REFRIGERACION Y PROYECTOS FRIOS', null, false),
  ('CONSTRUCTORA NAGIMOV', null, false),
  ('EZEQUIEL ALVARADO ARREDONDO', null, false),
  ('MARIA DEL CARMEN FERNANDEZ AVILA', null, false),
  ('Herrajes Bulnes de Occidente S.A. de C.V.', null, false),
  ('HOME DEPOT MEXICO S. DE R.L. DE C.V.', null, false),
  ('RED LINEA', null, false),
  ('SONIGAS', null, false),
  ('MARISOL HERNANDEZ ROBLES', null, false),
  ('Carlos Alan Zatarain Coronado', null, false),
  ('XOCHILT BARCENAS GOMEZ', null, false),
  ('ANA BERTHA RODRIGUEZ MARTINEZ', null, false),
  ('ROSA LYDIA DEL TORO MARTINEZ', null, false),
  ('Nueva Wal Mart de México', null, false),
  ('GRUPO RAMLO', null, false),
  ('CADENA COMERCIAL OXXO SA DE CV', null, false),
  ('MARTIN HERNANDEZ NEGRETE', null, false),
  ('JOSE ALFREDO ARIAS BARRON', null, false),
  ('MIGUEL ANGEL LOPEZ GARCIA', null, false),
  ('ZULEMA SANJUANITA RUIZ MORENO', null, false),
  ('ISRAEL CUEVAS HERRERA', null, false),
  ('MARCEL ANTONIO RODRIGUEZ AYACHE', null, false),
  ('RED DE CARRETERAS DE OCCIDENTE SAB DE CV', null, false),
  ('ELECTRONICA DE LEON', null, false),
  ('GABRIEL BECERRA VALDEZ', null, false),
  ('MARIA PATRICIA MATIAS CRUZ', null, false),
  ('ARACELI LOPEZ MIRANDA', null, false),
  ('NO DEDUCIBLE', null, false),
  ('JUAN FRANCISCO MOLINA CHARLES', null, false),
  ('JOSE LUIS CLEMENTE DIAZ', null, false),
  ('MARISELA ESQUIVEL TOMAS', null, false),
  ('JOSE CESAR MAGDALENO GONZALEZ', null, false),
  ('RUBEN OMAR CASTRO CORIA', null, false),
  ('CLEMENTE BARRIOS VIVEROS', null, false),
  ('OSCAR ALBERTO RAMIREZ MEDINA', null, false),
  ('INGENIERIA Y ELECTROMECANICA GUERRERO', null, false),
  ('IVAN RAMON CRUZ RODRIGUEZ', null, false),
  ('LUIS ALBERTO RODRIGUEZ RUBIO', null, false),
  ('FRANCISCO JAVIER MACIAS ARIAS', null, false),
  ('DAVID RICARDO CERDA GOMEZ', null, false),
  ('SVPO', null, false),
  ('CONSTRUCTORA PUENTE AL FUTURO', null, false),
  ('GASTRONOMIA SANCHO DE AGUASCALIENTES, SA DE CV', null, false),
  ('OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFICACION SA DE CV', null, false),
  ('RESTAURANTES ADMX S DE RL DE CV', null, false),
  ('PREMIUM RESTAURANT BRANDS S DE RL DE CV', null, false),
  ('RICHYCARLS SA DE CV', null, false),
  ('GDL', null, true),
  ('HMO', null, true),
  ('CUU', null, true),
  ('CD juarez', null, true),
  ('Leon', null, true),
  ('AGS', null, true),
  ('LEON', null, true),
  ('Sucursales', null, true)
on conflict (nombre) do nothing;

-- gastos
insert into gastos (fecha, sucursal_id, proveedor_id, concepto, tipo, unidad_pago, estatus_pago, cotizaciones, monto, requiere_revision, nota_revision)
select v.fecha::date, s.id, p.id, v.concepto, v.tipo::tipo_mantenimiento, v.unidad::unidad_pago,
       v.estatus::estatus_pago, v.cot, v.monto, v.revision, v.nota
from (values
  ('2026-01-27', 'LEO', 'CONSTRUCTORA HESSE SAJONIA', 'reparaciones y modificacion de tarja leon pago anticipado', 'remodelacion', 'compania', 'pagado', 3, 11965.44::numeric, false, null),
  ('2026-01-27', 'GDL', 'GRUPO BRAGA OPORTO', 'Materiales reparaciones cedis pago anticipado', 'preventivo', 'compania', 'pagado', 2, 6245::numeric, false, null),
  ('2026-01-27', 'GDL', 'GRUPO BRAGA OPORTO', 'Materiales para reparaciones cedis pago anticipado', 'preventivo', 'compania', 'pagado', 1, 11070::numeric, false, null),
  ('2026-01-26', 'GDL', 'REFACCIONARIA FERRETERA SA DE CV', 'refacciones cedis', 'preventivo', 'caja_chica', 'pagado', 1, 348.88::numeric, false, null),
  ('2026-01-26', 'GDL', 'ADHESELLA Y COMPLEMENTOS', 'materiales y adhesivo cedis', 'preventivo', 'caja_chica', 'pagado', 1, 455.33::numeric, false, null),
  ('2026-01-26', 'CUU', 'GAS EL SOBRANTE', 'gas LP calefaccion chihuahua', 'insumo', 'compania', 'pagado', 1, -4000::numeric, true, 'Monto capturado en negativo en el Excel original. Confirmar si es nota de credito o error de captura.'),
  ('2026-01-22', 'AGS', 'JOSE GUADALUPE RAMIREZ AGUAYO', 'desasolve de drenaje aguascalientes', 'correctivo', 'compania', 'pagado', 3, 3680::numeric, false, null),
  ('2026-01-22', 'AGS', 'JOSE GUADALUPE RAMIREZ AGUAYO', 'reparacion de drenaje tapado aguscalientes', 'correctivo', 'compania', 'pagado', 3, 2260::numeric, false, null),
  ('2026-01-20', 'LEO', 'CONSTRUCCIONES Y REMODELACIONES SAN', 'servicio de apoyo para la instalacion de racks y estantes suc. leon', 'remodelacion', 'compania', 'pagado', 3, 9327::numeric, false, null),
  ('2026-01-20', 'LEO', 'CONSTRUCCIONES Y REMODELACIONES SAN', 'montaje de malla ciclonica para suc. leon', 'remodelacion', 'compania', 'pagado', 5, 46320::numeric, false, null),
  ('2026-01-20', 'GDL', 'DISTRIBUIDORA PINTA FAMM S.A. DE C.V.', 'lijas y thiner amapola', 'preventivo', 'caja_chica', 'pagado', 1, 392.24::numeric, false, null),
  ('2026-01-19', 'CDJ', 'MARBUS MKT', 'servicio de mantenimiento correctivoa engranaje de sistema cortina metálica', 'correctivo', 'compania', 'aprobado', 2, 4260::numeric, false, null),
  ('2026-01-14', 'GDL', 'REFACCIONARIA FERRETERA SA DE CV', 'broca para puertas de insumos cafe', 'preventivo', 'caja_chica', 'pagado', 1, 318.21::numeric, false, null),
  ('2026-01-12', 'GDL', 'LUIS ALBERTO ARROYO CHAVEZ', 'pago de servicio y desmantelamiento trituradoras de papel', 'correctivo', 'caja_chica', 'pagado', 2, 2068.97::numeric, false, null),
  ('2026-01-12', 'HMO', 'INGENIERIA Y MOVILIDAD URBANA IMU SA DE CV', 'Reparación y reprogramacion de pluma de acceso Hmo', 'correctivo', 'caja_chica', 'pagado', 2, 1100::numeric, false, null),
  ('2026-01-09', 'CUU', 'GAS EL SOBRANTE', 'comprobacion de gasto informe 170101 GAS lp Chihuahua', 'insumo', 'compania', 'aprobado', 1, 3460.01::numeric, false, null),
  ('2026-01-07', 'CDJ', 'JORGE LUIS REYES ADRIANO', 'reparación de cortina metalica cd juarez peatonal', 'correctivo', 'compania', 'pagado', 2, 3200::numeric, false, null),
  ('2026-01-06', 'GDL', 'GRUPO BRAGA OPORTO', 'Materiales para oficinas cedis', 'correctivo', 'caja_chica', 'pagado', 1, 9618::numeric, false, null),
  ('2026-01-05', 'CUU', 'GAS EL SOBRANTE', 'Recarga de GAS lp Sucursal Chihuahua', 'insumo', 'compania', 'pagado', 0, -4000::numeric, true, 'Monto capturado en negativo en el Excel original. Confirmar si es nota de credito o error de captura.'),
  ('2026-02-26', 'LEO', 'DAVID ALMENDRA GUZMAN', 'extensiones electricas para lugares leon', 'remodelacion', 'caja_chica', 'pagado', 1, 1760.34::numeric, false, null),
  ('2026-02-26', 'LEO', 'DAVID ALMENDRA GUZMAN', 'compra de candados de seguridad', 'remodelacion', 'caja_chica', 'pagado', 1, 660::numeric, false, null),
  ('2026-02-26', 'LEO', 'JESUS BALDERAS ROJAS', 'Reparacion urgente por corto electrico', 'correctivo', 'caja_chica', 'pagado', 1, 1810.34::numeric, false, null),
  ('2026-02-26', 'LEO', 'DAVID ALMENDRA GUZMAN', 'servicio de cerrajeria duplicados leon', 'remodelacion', 'caja_chica', 'pagado', 1, 94.83::numeric, false, null),
  ('2026-02-27', 'GDL', 'REFACCIONARIA FERRETERA SA DE CV', 'candado metalico jaula industrial', 'preventivo', 'caja_chica', 'pagado', 1, 199.36::numeric, false, null),
  ('2026-02-25', 'GDL', 'REFACCIONARIA FERRETERA SA DE CV', 'conecciones hidraulicas amapola comedor', 'preventivo', 'caja_chica', 'pagado', 1, 444.91::numeric, false, null),
  ('2026-02-25', 'LEO', 'REFRIGERACION Y PROYECTOS FRIOS', 'control remoto universal a/a', 'correctivo', 'caja_chica', 'pagado', 1, 300::numeric, false, null),
  ('2026-02-24', 'CUU', 'GAS EL SOBRANTE', 'comprobacion del informe172,179 por gasto anticipado', 'insumo', 'compania', 'pagado', 1, 3445.17::numeric, false, null),
  ('2026-02-23', 'CUU', 'MARBUS MKT', 'Chihuahua reparaciones de reja principal', 'correctivo', 'compania', 'pagado', 2, 13520::numeric, false, null),
  ('2026-02-23', 'CDJ', 'MARBUS MKT', 'cd juarez reparaciones por daños en muros', 'correctivo', 'compania', 'pagado', 2, 14611::numeric, false, null),
  ('2026-02-18', 'LEO', 'CONSTRUCTORA NAGIMOV', 'informe 172179 comprobación con factura de pago anticipado', 'otro', 'compania', 'pagado', 2, 8064::numeric, false, null),
  ('2026-02-17', 'LEO', 'CONSTRUCTORA NAGIMOV', 'informe 172179 comprobación con factura de pago anticipado', 'otro', 'compania', 'pagado', 2, 8064::numeric, false, null),
  ('2026-02-20', 'LEO', 'EZEQUIEL ALVARADO ARREDONDO', 'viaticos leon, cena 20/02/2026', 'viaticos', 'empleado', 'pagado', 0, 120.68::numeric, false, null),
  ('2026-02-19', 'LEO', 'MARIA DEL CARMEN FERNANDEZ AVILA', 'materiales para pegar letreros', 'preventivo', 'caja_chica', 'pagado', 1, 112.19::numeric, false, null),
  ('2026-02-17', 'CUU', 'GAS EL SOBRANTE', '170931 comprobacion de gasto recarga de gas LP', 'otro', 'compania', 'pagado', 1, 3447.88::numeric, false, null),
  ('2026-02-17', 'GDL', 'Herrajes Bulnes de Occidente S.A. de C.V.', 'pegamento y cerradura de cajon amapola', 'preventivo', 'caja_chica', 'pagado', 1, 375.38::numeric, false, null),
  ('2026-01-01', 'LEO', 'CONSTRUCTORA NAGIMOV', 'pago anticipado mantenimiento y reparacion de cortinasmetalicas leon', 'preventivo', 'compania', 'aprobado', 1, 0::numeric, true, 'Fecha ilegible en el Excel original; se asigno 2026-01-01.'),
  ('2026-02-16', 'LEO', 'CONSTRUCTORA HESSE SAJONIA', 'termino de trabajos, cinta y remplazo de poste leon', 'remodelacion', 'compania', 'pagado', 2, 10214::numeric, false, null),
  ('2026-02-16', 'LEO', 'CONSTRUCTORA HESSE SAJONIA', 'muro falso instalacion leon', 'remodelacion', 'compania', 'pagado', 2, 7153::numeric, false, null),
  ('2026-02-12', 'LEO', 'HOME DEPOT MEXICO S. DE R.L. DE C.V.', 'Compra de luminarias tipo t8 32w leon', 'remodelacion', 'caja_chica', 'pagado', 1, 703.45::numeric, false, null),
  ('2026-02-12', 'GDL', 'HOME DEPOT MEXICO S. DE R.L. DE C.V.', 'herrajes para tarja de cocineta leon', 'preventivo', 'caja_chica', 'pagado', 1, 272.84::numeric, false, null),
  ('2026-02-10', 'LEO', 'RED LINEA', 'servicio de mantenimiento a/a amapola', 'viaticos', 'compania', 'pagado', 3, 20720::numeric, false, null),
  ('2026-02-10', 'GDL', 'EZEQUIEL ALVARADO ARREDONDO', 'comida y cena viaje leon', 'correctivo', 'empleado', 'pagado', 0, 594.82::numeric, false, null),
  ('2026-02-10', 'GDL', 'Herrajes Bulnes de Occidente S.A. de C.V.', 'cerradura cuarto de limpieza amapola', 'insumo', 'caja_chica', 'a_enviar', 1, 410::numeric, false, null),
  ('2026-02-10', 'CUU', 'SONIGAS', 'Recarga de gas lp cedis', 'correctivo', 'caja_chica', 'pagado', 1, 862.11::numeric, false, null),
  ('2026-02-10', 'LEO', 'MARBUS MKT', 'Reparacion de drenaje y sellos de sanitario chihuahua', 'preventivo', 'compania', 'pagado', 1, 3400::numeric, false, null),
  ('2026-02-10', 'LEO', 'CONSTRUCTORA NAGIMOV', 'enjarre de cuarto especialista leon gto', 'viaticos', 'compania', 'pagado', 2, 16013::numeric, false, null),
  ('2026-02-10', 'LEO', 'MARISOL HERNANDEZ ROBLES', 'desayuno visita leon', 'viaticos', 'empleado', 'pagado', 0, 142.24::numeric, false, null),
  ('2026-02-10', 'HMO', 'MARISOL HERNANDEZ ROBLES', 'desayuno viaje leon 11/02/2026', 'preventivo', 'empleado', 'pagado', 0, 129.31::numeric, false, null),
  ('2026-02-09', 'CUU', 'Carlos Alan Zatarain Coronado', 'TRABAJOS PLOMERIA HMO', 'insumo', 'compania', 'pagado', 1, 3515.37::numeric, false, null),
  ('2026-01-01', 'GDL', 'GAS EL SOBRANTE', 'pago anticipado carga de gas chihuahua', 'correctivo', 'compania', 'aprobado', 1, 0::numeric, true, 'Fecha ilegible en el Excel original; se asigno 2026-01-01.'),
  ('2026-02-05', 'GDL', 'XOCHILT BARCENAS GOMEZ', 'refacturado de reparacion de trituradoras de papel', 'correctivo', 'compania', 'pagado', 1, 9380::numeric, false, null),
  ('2026-02-03', 'GDL', 'GRUPO BRAGA OPORTO', 'materiales ferreteria cedis', 'correctivo', 'compania', 'pagado', 1, 6336::numeric, false, null),
  ('2026-02-03', 'GDL', 'GRUPO BRAGA OPORTO', 'pintura negra para vigas cedis', 'correctivo', 'compania', 'pagado', 1, 9780::numeric, false, null),
  ('2026-03-31', 'AGS', 'ANA BERTHA RODRIGUEZ MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 248.28::numeric, false, null),
  ('2026-03-31', 'AGS', 'ANA BERTHA RODRIGUEZ MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 143.1::numeric, false, null),
  ('2026-03-31', 'AGS', 'ROSA LYDIA DEL TORO MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 248.28::numeric, false, null),
  ('2026-03-31', 'AGS', 'ROSA LYDIA DEL TORO MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 151.72::numeric, false, null),
  ('2026-03-31', 'AGS', 'ROSA LYDIA DEL TORO MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 362.07::numeric, false, null),
  ('2026-03-31', 'AGS', 'ANA BERTHA RODRIGUEZ MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 268.97::numeric, false, null),
  ('2026-03-31', 'AGS', 'ROSA LYDIA DEL TORO MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 210.34::numeric, false, null),
  ('2026-03-31', 'AGS', 'ANA BERTHA RODRIGUEZ MARTINEZ', 'consumo de alimentos viaje AGS', 'viaticos', 'empleado', 'pagado', 1, 184.48::numeric, false, null),
  ('2026-03-31', 'LEO', 'DAVID ALMENDRA GUZMAN', 'reparacion tarja regadera leon', 'correctivo', 'caja_chica', 'pagado', 1, 2600::numeric, false, null),
  ('2026-03-30', 'CUU', 'SONIGAS', 'Comprobante informe 171,423 ya pagado', 'insumo', 'compania', 'pagado', 1, 2586.65::numeric, false, null),
  ('2026-03-26', 'GDL', 'Nueva Wal Mart de México', 'compra de baterías AA/AAA Recepcion cedis', 'correctivo', 'caja_chica', 'pagado', 1, 498.28::numeric, false, null),
  ('2026-03-26', 'GDL', 'REFACCIONARIA FERRETERA SA DE CV', 'acido muriatico para limpieza de barra caliente cesdis', 'correctivo', 'caja_chica', 'pagado', 1, 174.02::numeric, false, null),
  ('2026-03-24', 'GDL', 'HOME DEPOT MEXICO S. DE R.L. DE C.V.', 'complementos de canaleta para instalacion de voz y datos. cedis', 'correctivo', 'caja_chica', 'pagado', 1, 173.28::numeric, false, null),
  ('2026-03-23', 'GDL', 'GRUPO RAMLO', 'compra de alarmas detectoras de gas cedis', 'correctivo', 'caja_chica', 'pagado', 1, 687.94::numeric, false, null),
  ('2026-03-23', 'GDL', 'CADENA COMERCIAL OXXO SA DE CV', 'compra de pilas para lavamanos, cedis', 'correctivo', 'caja_chica', 'pagado', 1, 124.94::numeric, false, null),
  ('2026-03-18', 'GDL', 'MARTIN HERNANDEZ NEGRETE', 'Reparación eléctrica de contactos', 'preventivo', 'caja_chica', 'pagado', 1, 1779.31::numeric, false, null),
  ('2026-03-18', 'HMO', 'JOSE ALFREDO ARIAS BARRON', 'Reparacion de cortina metalica hmo corectivo', 'correctivo', 'caja_chica', 'pagado', 1, 5210.34::numeric, false, null),
  ('2026-03-18', 'MTY', 'MIGUEL ANGEL LOPEZ GARCIA', 'reparacion electrica y remplazo de luminaria fundidasmty', 'correctivo', 'caja_chica', 'pagado', 1, 2979.31::numeric, false, null),
  ('2026-03-18', 'GDL', 'ADHESELLA Y COMPLEMENTOS', 'compra de silicon para ventanales', 'correctivo', 'caja_chica', 'pagado', 1, 1677.15::numeric, false, null),
  ('2026-03-17', 'AGS', 'ZULEMA SANJUANITA RUIZ MORENO', 'servicio de reparación en tarja y mangueras ags', 'correctivo', 'caja_chica', 'pagado', 1, 2200::numeric, false, null),
  ('2026-03-12', 'MTY', 'ISRAEL CUEVAS HERRERA', 'Reparacion de cambio de chapa,tapa, y destapado de drenaje mty', 'correctivo', 'caja_chica', 'pagado', 1, 3582.76::numeric, false, null),
  ('2026-03-11', 'LEO', 'MARCEL ANTONIO RODRIGUEZ AYACHE', 'comida viaticos leon', 'viaticos', 'empleado', 'pagado', 1, 140.52::numeric, false, null),
  ('2026-03-11', 'GDL', 'REFACCIONARIA FERRETERA SA DE CV', 'manguera 6cp candado y cadena', 'preventivo', 'caja_chica', 'pagado', 1, 829.15::numeric, false, null),
  ('2026-03-11', 'LEO', 'RED DE CARRETERAS DE OCCIDENTE SAB DE CV', 'desayuno leon viaje', 'viaticos', 'empleado', 'pagado', 1, 318.58::numeric, false, null),
  ('2026-03-11', 'LEO', 'ELECTRONICA DE LEON', 'control universal ELECTRONICA DE LEON', 'correctivo', 'caja_chica', 'pagado', 1, 223.28::numeric, false, null),
  ('2026-03-11', 'HMO', 'GABRIEL BECERRA VALDEZ', 'cambio de chapa aluminio, almacen HMO', 'preventivo', 'caja_chica', 'a_enviar', 1, 1200::numeric, false, null),
  ('2026-03-10', 'HMO', 'MARBUS MKT', 'Servicio de mantenimiento preventico a/a hmo', 'preventivo', 'compania', 'pagado', 1, 12340::numeric, false, null),
  ('2026-03-09', 'AGS', 'MARIA PATRICIA MATIAS CRUZ', 'comida gastos viaje ags', 'viaticos', 'empleado', 'pagado', 1, 210.34::numeric, false, null),
  ('2026-03-09', 'LEO', 'MARIA PATRICIA MATIAS CRUZ', 'comida viaje leon traslado', 'viaticos', 'empleado', 'pagado', 1, 244.83::numeric, false, null),
  ('2026-03-09', 'LEO', 'MARIA PATRICIA MATIAS CRUZ', 'alimentos viaticos viaje leon', 'viaticos', 'empleado', 'pagado', 1, 244.83::numeric, false, null),
  ('2026-03-09', 'LEO', 'MARIA PATRICIA MATIAS CRUZ', 'alimentos viaticos viaje leon', 'viaticos', 'empleado', 'pagado', 1, 244.83::numeric, false, null),
  ('2026-03-09', 'LEO', 'MARIA PATRICIA MATIAS CRUZ', 'comidas viaje leon traslado', 'viaticos', 'empleado', 'pagado', 1, 269.83::numeric, false, null),
  ('2026-03-09', 'LEO', 'MARIA PATRICIA MATIAS CRUZ', 'alimentos viaticos viaje leon', 'viaticos', 'empleado', 'pagado', 1, 241.38::numeric, false, null),
  ('2026-03-09', 'LEO', 'CONSTRUCTORA HESSE SAJONIA', 'Remplazo de sanitario y reparacion de puerta', 'preventivo', 'compania', 'pagado', 1, 11624::numeric, false, null),
  ('2026-03-09', 'AGS', 'ARACELI LOPEZ MIRANDA', 'desayuno viaje ags', 'viaticos', 'empleado', 'pagado', 1, 189.66::numeric, false, null),
  ('2026-03-05', 'CDJ', 'GAS EL SOBRANTE', 'Comprobación de gasto informe 172,904 recarga de gas lp ciudad juarez', 'insumo', 'compania', 'pagado', 1, 3703.7::numeric, false, null),
  ('2026-03-04', 'GDL', 'NO DEDUCIBLE', 'compra de componente eléctrico para tarjeta de a/a', 'correctivo', 'caja_chica', 'pagado', 1, 0::numeric, false, null),
  ('2026-03-03', 'LEO', 'REFACCIONARIA FERRETERA SA DE CV', 'silicon para pegar letreros de symma en leon', 'preventivo', 'caja_chica', 'pagado', 1, 215.21::numeric, false, null),
  ('2026-03-03', 'LEO', 'GRUPO BRAGA OPORTO', 'materiales para sellar uniones de muros cedis', 'correctivo', 'compania', 'pagado', 1, 10837.5::numeric, false, null),
  ('2026-03-03', 'LEO', 'GRUPO BRAGA OPORTO', 'Materiales para pintar area comedor cedis', 'preventivo', 'compania', 'pagado', 1, 14299::numeric, false, null),
  ('2026-03-03', 'CDJ', 'GAS EL SOBRANTE', 'recarga de gas CD juarez pago anticipado', 'preventivo', 'compania', 'pagado', 1, 0::numeric, false, null),
  ('2026-03-02', 'LEO', 'REFACCIONARIA FERRETERA SA DE CV', 'compra de materiales destapacaños', 'preventivo', 'caja_chica', 'pagado', 1, 384.92::numeric, false, null),
  ('2026-04-30', 'HMO', 'JUAN FRANCISCO MOLINA CHARLES', 'configuracion de pluma electrica hmo', 'correctivo', 'caja_chica', 'pagado', 1, 1100::numeric, false, null),
  ('2026-04-30', 'AGS', 'JOSE LUIS CLEMENTE DIAZ', 'reparacion electrica por fallas', 'correctivo', 'caja_chica', 'pagado', 1, 3135.34::numeric, false, null),
  ('2026-04-30', 'GDL', 'JOSE ALFREDO ARIAS BARRON', 'material para sello de lamina almacen', 'correctivo', 'caja_chica', 'pagado', 1, 3354.3::numeric, false, null),
  ('2026-04-30', 'HMO', 'MARISELA ESQUIVEL TOMAS', 'comida viaticos hmo', 'viaticos', 'empleado', 'pagado', 1, 771.55::numeric, false, null),
  ('2026-04-30', 'HMO', 'JOSE CESAR MAGDALENO GONZALEZ', 'comida viaje viaticos', 'viaticos', 'empleado', 'pagado', 1, 538.79::numeric, false, null),
  ('2026-04-21', 'LEO', 'RUBEN OMAR CASTRO CORIA', 'Servicio de verificación de instalaciones elctricas', 'correctivo', 'caja_chica', 'pagado', 1, 900::numeric, false, null),
  ('2026-04-20', 'GDL', 'CLEMENTE BARRIOS VIVEROS', 'serviciod e reparacion de display bascula', 'correctivo', 'caja_chica', 'pagado', 1, 2100::numeric, false, null),
  ('2026-04-20', 'GDL', 'OSCAR ALBERTO RAMIREZ MEDINA', 'materiales para sellado de grietas juntas', 'correctivo', 'caja_chica', 'pagado', 1, 1648::numeric, false, null),
  ('2026-04-20', 'HMO', 'JOSE ALFREDO ARIAS BARRON', 'reparacion de chapa por base rota amapola', 'correctivo', 'caja_chica', 'pagado', 1, 1780::numeric, false, null),
  ('2026-04-14', 'AGS', 'INGENIERIA Y ELECTROMECANICA GUERRERO', 'Reparacion de sistema de desague incluye materiales y mano de obra', 'correctivo', 'caja_chica', 'pagado', 1, 1600::numeric, false, null),
  ('2026-04-07', 'GDL', 'RED LINEA', 'servicio de mantenimiento en amapola', 'correctivo', 'compania', 'pagado', 3, 25300::numeric, false, null),
  ('2026-05-27', 'CUU', 'IVAN RAMON CRUZ RODRIGUEZ', 'fallas eléctricas chihuahua', 'correctivo', 'caja_chica', 'pagado', 1, 4000::numeric, false, null),
  ('2026-05-25', 'GDL', 'LUIS ALBERTO RODRIGUEZ RUBIO', 'reparacion de microhondas caseta amapola', 'correctivo', 'caja_chica', 'pagado', 1, 350::numeric, false, null),
  ('2026-05-19', 'LEO', 'INGENIERIA Y ELECTROMECANICA GUERRERO', 'reparacion fuga de baño y mal olor leon gto', 'correctivo', 'caja_chica', 'pagado', 1, 1400::numeric, false, null),
  ('2026-05-16', 'GDL', 'FRANCISCO JAVIER MACIAS ARIAS', 'soldadura de porton y base para acometida de cableado cedis', 'correctivo', 'caja_chica', 'pagado', 1, 2000::numeric, false, null),
  ('2026-05-12', 'CUU', 'MARBUS MKT', 'reparacion hidro cuu', 'correctivo', 'caja_chica', 'pagado', 1, 3100::numeric, false, null),
  ('2026-05-12', 'CUU', 'MARBUS MKT', 'reparacion hidro 2 cuu', 'correctivo', 'caja_chica', 'pagado', 1, 3100::numeric, false, null),
  ('2026-05-12', 'CUU', 'MARBUS MKT', 'servicio de limpieza aljibe', 'correctivo', 'caja_chica', 'pagado', 2, 4650::numeric, false, null),
  ('2026-05-12', 'CUU', 'MARBUS MKT', 'servicio de limpieza 2 tinacos', 'correctivo', 'caja_chica', 'pagado', 2, 4650::numeric, false, null),
  ('2026-06-30', 'AGS', 'DAVID RICARDO CERDA GOMEZ', 'remplazo de bomba de agua dañada', 'correctivo', 'compania', 'pagado', 1, 9490::numeric, false, null),
  ('2026-06-30', 'AGS', 'SVPO', 'viaticos aguascalientes cierre', 'correctivo', 'empleado', 'pagado', 1, 351.71::numeric, false, null),
  ('2026-06-25', 'AGS', 'CONSTRUCCIONES Y REMODELACIONES SAN', 'suministro y remplazo de sistemas hidrosanitarios', 'correctivo', 'compania', 'pagado', 2, 5808::numeric, false, null),
  ('2026-06-26', 'AGS', 'CONSTRUCTORA PUENTE AL FUTURO', 'sservicio de mantenimiento y reparacion equipos a/a', 'correctivo', 'compania', 'pagado', 1, 7240::numeric, false, null),
  ('2026-06-26', 'AGS', 'CONSTRUCTORA PUENTE AL FUTURO', 'Reparacion nivel de cortina y sensor', 'correctivo', 'compania', 'pagado', 2, 6320::numeric, false, null),
  ('2026-06-22', 'AGS', 'GASTRONOMIA SANCHO DE AGUASCALIENTES, SA DE CV', 'VIATICOS CIERRE AGS', 'viaticos', 'empleado', 'pagado', 1, 103.45::numeric, false, null),
  ('2026-06-19', 'AGS', 'OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFICACION SA DE CV', 'viáticos viaje cierre aguascalientes', 'viaticos', 'empleado', 'pagado', 1, 132.76::numeric, false, null),
  ('2026-06-18', 'AGS', 'GRUPO BRAGA OPORTO', 'materiales para sello de azotea almacen', 'viaticos', 'caja_chica', 'pagado', 1, 2294.4::numeric, false, null),
  ('2026-06-18', 'AGS', 'GRUPO BRAGA OPORTO', 'materiales para sello de azotea almacen', 'viaticos', 'caja_chica', 'pagado', 1, 708::numeric, false, null),
  ('2026-06-18', 'AGS', 'GRUPO BRAGA OPORTO', 'materiales para sello de azotea almacen', 'viaticos', 'caja_chica', 'pagado', 1, 3817::numeric, false, null),
  ('2026-06-19', 'AGS', 'SVPO', 'viáticos viaje cierre aguascalientes', 'viaticos', 'empleado', 'pagado', 1, 342.23::numeric, false, null),
  ('2026-06-19', 'AGS', 'RESTAURANTES ADMX S DE RL DE CV', 'viáticos viaje cierre aguascalientes', 'viaticos', 'empleado', 'pagado', 1, 284.48::numeric, false, null),
  ('2026-06-19', 'AGS', 'PREMIUM RESTAURANT BRANDS S DE RL DE CV', 'viáticos viaje cierre aguascalientes', 'viaticos', 'empleado', 'pagado', 1, 119.83::numeric, false, null),
  ('2026-06-19', 'AGS', 'PREMIUM RESTAURANT BRANDS S DE RL DE CV', 'viáticos viaje cierre aguascalientes', 'viaticos', 'empleado', 'pagado', 1, 298.28::numeric, false, null),
  ('2026-06-19', 'AGS', 'RICHYCARLS SA DE CV', 'viáticos viaje cierre aguascalientes', 'viaticos', 'empleado', 'pagado', 1, 372.41::numeric, false, null),
  ('2026-06-04', 'AGS', 'Herrajes Bulnes de Occidente S.A. de C.V.', 'Chapa electrica peatonal amapola', 'correctivo', 'caja_chica', 'pagado', 1, 1095.41::numeric, false, null),
  ('2026-06-02', 'AGS', 'LUIS ALBERTO ARROYO CHAVEZ', 'Reparacion electrica de tarjeta a/a mostrador #3', 'correctivo', 'caja_chica', 'pagado', 2, 5431.03::numeric, false, null),
  ('2026-06-02', 'AGS', 'LUIS ALBERTO ARROYO CHAVEZ', 'Reparacion electrica de tarjetas de motores cortinas almacen #5', 'correctivo', 'caja_chica', 'pagado', 2, 6637.93::numeric, false, null)
) as v(fecha, codigo, proveedor, concepto, tipo, unidad, estatus, cot, monto, revision, nota)
join sucursales s on s.codigo = v.codigo
left join proveedores p on p.nombre = v.proveedor;

-- ==================================================================
-- ACTIVOS
-- ==================================================================
insert into activos (sucursal_id, categoria_id, codigo, nombre, ubicacion, tipo, marca, modelo, serie, capacidad, criticidad, fecha_instalacion, ultimo_servicio, atributos, notas)
select s.id, c.id, v.codigo, v.nombre, v.ubicacion, v.tipo, v.marca, v.modelo, v.serie, v.capacidad,
       v.criticidad::criticidad_activo, v.finst::date, v.ultimo::date, v.attrs::jsonb, v.notas
from (values
  ('GDL', 'Aire Acondicionado', 'AA-001', 'Mini split — CASETA DE VIGILANCIA', 'CASETA DE VIGILANCIA', 'Mini split', 'PRIME', 'CMPRC362-W', null, '36000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T1-T01-TD04/C10-C12","interruptor":"Doble 32 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-002', 'Mini split — RECEPCION', 'RECEPCION', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD02/C11-C13","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-003', 'Mini split — SALA AGUASCALIENTES', 'SALA AGUASCALIENTES', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD02/C12-C14","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-004', 'Mini split — ENFERMERIA', 'ENFERMERIA', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD02/C15-C17","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-005', 'Mini split — SITE 1', 'SITE 1', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C09","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-006', 'Manejadora — MOSTRADOR PLANTA BAJA', 'MOSTRADOR PLANTA BAJA', 'Manejadora', 'DAIKIN', 'ASPT49D14AC', null, '48000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C10","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-007', 'Manejadora — MOSTRADOR PLANTA ALTA', 'MOSTRADOR PLANTA ALTA', 'Manejadora', 'DAIKIN', 'ASPT49D14AC', null, '48000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C11","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-008', 'Mini split — SALA AMAPOLA', 'SALA AMAPOLA', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C12","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-009', 'Mini split — CAJA MOSTRADOR', 'CAJA MOSTRADOR', 'Mini split', 'DAIKIN', 'FTKS245L217', null, '18001 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"221 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C13","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-009', 'Mini split — GERENCIA ALMACEN', 'GERENCIA ALMACEN', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C13","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-010', 'Manejadora — SOPORTE IT', 'SOPORTE IT', 'Manejadora', 'DAIKIN', 'ASPT49D14AC', null, '48000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C14","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-011', 'Mini split — DATA CENTER 2', 'DATA CENTER 2', 'Mini split', 'MIRAGE', 'CMC361N', null, '36000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C15","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-012', 'Mini split — DATA CENTER 2', 'DATA CENTER 2', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '18000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C16","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-013', 'Manejadora — PASILLO 2 PLANTA', 'PASILLO 2 PLANTA', 'Manejadora', 'DAIKIN', 'ASPT49D14AC', null, '48000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C17","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-014', 'Mini split — INGENIERIA P1C', 'INGENIERIA P1C', 'Mini split', 'DAIKIN', 'ITKS245L216', null, '36000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C18","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-015', 'Mini split — SALA JUAREZ', 'SALA JUAREZ', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '36000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C19","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-016', 'Mini split — COTIZACIONES P1C', 'COTIZACIONES P1C', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C20","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-017', 'Mini split — GERENCIA P1C', 'GERENCIA P1C', 'Mini split', 'MIRAGE', null, null, '12000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","tablero":"T2-T01-TD11/C07-C21","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-018', 'Mini split — DIRECCION P1C', 'DIRECCION P1C', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C22","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-019', 'Manejadora — CAPITAL HUMANO', 'CAPITAL HUMANO', 'Manejadora', 'DAIKIN', 'ASPT49D14AC', null, '47999 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"219 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C23","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-020', 'Manejadora — COMEDOR', 'COMEDOR', 'Manejadora', 'DAIKIN', 'ASPT49D14AC', null, '48000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C24","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-021', 'Mini split — GERENCIA CAPITAL HUMANO', 'GERENCIA CAPITAL HUMANO', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C25","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-022', 'Mini split — AREA LEGAL', 'AREA LEGAL', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C26","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-023', 'Mini split — GERENCIA MERKADOTECNIA', 'GERENCIA MERKADOTECNIA', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '36000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C27","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-024', 'Mini split — DIRECCION ADMINISTRATIVA', 'DIRECCION ADMINISTRATIVA', 'Mini split', 'DUVENTUS', 'OVR9M121F001', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C28","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-025', 'Mini split — DIRECCION OPERATIVA', 'DIRECCION OPERATIVA', 'Mini split', 'DAIKIN', 'FTKS245L216', null, '36000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","tablero":"T2-T01-TD11/C07-C29","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-026', 'Mini split — DIRECCION', 'DIRECCION', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C30","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-027', 'Mini split — DIRECCION GENERAL', 'DIRECCION GENERAL', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C31","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-028', 'Mini split — DIRECCION FINANZAS', 'DIRECCION FINANZAS', 'Mini split', 'PRIME', 'CMPRC122K', null, '12001 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"221 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C32","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-029', 'Manejadora — GENERAL VENTAS 1', 'GENERAL VENTAS 1', 'Manejadora', 'MIRAGE', 'SMCC1221D', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R22","tablero":"T2-T01-TD11/C07-C33","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-030', 'Manejadora — GENERAL VENTAS 2', 'GENERAL VENTAS 2', 'Manejadora', 'FREYVEN', '38FYCR3A', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C34","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-031', 'Manejadora — GENERAL VENTAS 3', 'GENERAL VENTAS 3', 'Manejadora', 'CARRIER', '38C1Q183AC', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220 V","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C35","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-032', 'Manejadora — GENERAL VENTAS 4', 'GENERAL VENTAS 4', 'Manejadora', 'FREYVEN', '38FYCR3A', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C36","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-033', 'Mini split — GERENCIA DE CREDITO Y COBRANZA', 'GERENCIA DE CREDITO Y COBRANZA', 'Mini split', 'PRIME', 'CMPRC122K', null, '12000 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C37","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-034', 'Mini split — GERENCIA CUENTAS POR PAGAR', 'GERENCIA CUENTAS POR PAGAR', 'Mini split', 'PRIME', 'CMPRC122K', null, '12001 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C38","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-035', 'Mini split — GERENCIAFINANZAS', 'GERENCIAFINANZAS', 'Mini split', 'PRIME', 'CMPRC122K', null, '12002 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C39","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-036', 'Mini split — GERENCIA NOMINAS', 'GERENCIA NOMINAS', 'Mini split', 'PRIME', 'CMPRC122K', null, '12003 BTU', 'B', null, '2026-11-02', '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C40","interruptor":"Doble 20 amp"}', 'REALIZADO 11/02/2026'),
  ('GDL', 'Aire Acondicionado', 'AA-037', 'Mini split — DIRECCION ELECTRICA', 'DIRECCION ELECTRICA', 'Mini split', 'PRIME', 'CMPRC122K', null, '12004 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C41","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-038', 'Mini split — SUB DIRECTOR DE LINEAS ELECTRICAS', 'SUB DIRECTOR DE LINEAS ELECTRICAS', 'Mini split', 'PRIME', 'CMPRC122K', null, '12005 BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"R410 A","tablero":"T2-T01-TD11/C07-C42","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-039', 'N/A — Extractor 1', 'Extractor 1', 'N/A', 'N/A', 'N/A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C43","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-040', 'N/A — Extractor 2', 'Extractor 2', 'N/A', 'N/A', 'N/A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C44","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-041', 'N/A — Extractor 3', 'Extractor 3', 'N/A', 'N/A', 'N/A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C45","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-042', 'N/A — Extractor 4', 'Extractor 4', 'N/A', 'N/A', 'N/A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C46","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-043', 'N/A — Extractor mediano 1', 'Extractor mediano 1', 'N/A', 'Fantech', '5BDU30KX-A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C47","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-044', 'N/A — Extractor mediano 2', 'Extractor mediano 2', 'N/A', 'Fantech', '5BDU30KX-A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C48","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-045', 'N/A — Extractor mediano 3', 'Extractor mediano 3', 'N/A', 'Fantech', '5BDU30KX-A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C49","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-046', 'N/A — Extractor mediano 4', 'Extractor mediano 4', 'N/A', 'Fantech', '5BDU30KX-A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C50","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-047', 'N/A — Extractor mediano 5', 'Extractor mediano 5', 'N/A', 'Fantech', '5BDU30KX-A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C51","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-048', 'N/A — Extractor mediano 6', 'Extractor mediano 6', 'N/A', 'Fantech', '5BDU30KX-A', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"220v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C52","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-049', 'ventilador — Extractor P1C 1', 'Extractor P1C 1', 'ventilador', 'systemair', 'W3G560-DQ41-06', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"480v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C53","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-050', 'ventilador — Extractor P1C 2', 'Extractor P1C 2', 'ventilador', 'systemair', 'W3G560-DQ41-06', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"480v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C54","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-051', 'ventilador — Extractor P1C 3', 'Extractor P1C 3', 'ventilador', 'systemair', 'W3G560-DQ41-06', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"480v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C55","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Aire Acondicionado', 'AA-052', 'ventilador — Extractor P1C 4', 'Extractor P1C 4', 'ventilador', 'systemair', 'W3G560-DQ41-06', null, 'N/A BTU', 'B', null, null, '{"corriente":"17.45 AMP","voltaje":"480v","refrigerante":"N/A","tablero":"T2-T01-TD11/C07-C56","interruptor":"Doble 20 amp"}', null),
  ('GDL', 'Equipos Electricos', 'EE-101', 'MOTOR PORTON PATIO DE MANIOBRAS', null, null, 'FAAC', 'FAAC 844 Z28', null, '900 kg', 'A', null, null, '{"electrica":"220v / 240v","aceite":"Tipo de aceite: FAAC HP OIL"}', null),
  ('GDL', 'Equipos Electricos', 'EE-102', 'MOTOR PORTON PERSONAL', null, null, 'MARATHON', 'OTBH', '161017019', '2 hp', 'A', null, null, '{"electrica":"208V"}', null),
  ('GDL', 'Equipos Electricos', 'EE-103', 'BOMBA SUMERGIBLE 1', null, null, 'VEVOR', null, null, '7 hp', 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-104', 'BOMBA SUMERGIBLE 2', null, null, 'VEVOR', null, null, '7hp', 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-105', 'BOMBA CARCAMO 1', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-106', 'BOMBA CARCAMO 2', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-107', 'BOMBA CARCAMO 3', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-108', 'BOMBA CARCAMO 4', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-109', 'COMPRESOR', null, null, 'cbs', null, '516516', '500L', 'A', null, null, '{"electrica":"110V/3.8 AMP","aceite":"3.5 hidraulico"}', null),
  ('GDL', 'Equipos Electricos', 'EE-110', 'PORTON DE PISTONES R. MICHEL', null, null, null, null, null, null, 'A', null, null, '{"electrica":"110v","aceite":"1.7 hidraulico"}', null),
  ('GDL', 'Equipos Electricos', 'EE-111', 'MOTOR CORTINA 1', null, null, 'MANARAS OMH', 'MANARAS OPH', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('GDL', 'Equipos Electricos', 'EE-112', 'MOTOR CORTINA 2', null, null, 'LiftMaster', 'MH5011UR', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('GDL', 'Equipos Electricos', 'EE-113', 'MOTOR CORTINA 3', null, null, 'LiftMaster', 'MH5011UR', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('GDL', 'Equipos Electricos', 'EE-114', 'MOTOR CORTINA 4', null, null, 'LiftMaster', 'MH5011UR', '2115N6685', '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('GDL', 'Equipos Electricos', 'EE-115', 'MOTOR CORTINA 5', null, null, 'MANARAS OMH', 'MANARAS OPH', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('GDL', 'Equipos Electricos', 'EE-116', 'MOTOR CORTINA 6', null, null, 'MANARAS', 'MH5011ER', '2017N2588', null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-117', 'MOTOR CORTINA 7', null, null, null, null, '2918N4624', null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-118', 'MOTOR CORTINA 8', null, null, null, null, '5018N6654', null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-121', 'ANDEN 1', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-122', 'ANDEN 2', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-123', 'ANDEN 3', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-124', 'ANDEN 4', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-125', 'ANDEN 5', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-126', 'ANDEN 6', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-129', 'ELEVADOR DE CARGA 1', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('GDL', 'Equipos Electricos', 'EE-130', 'ELEVADOR DE CARGA 2', null, null, null, null, null, null, 'A', null, null, '{}', null),
  ('CUU', 'Equipos Electricos', 'EE-101', 'MOTOR PORTON PATIO DE MANIOBRAS', null, null, 'FAAC', 'FAAC 844 Z28', null, '900 kg', 'A', null, null, '{"electrica":"220v / 240v","aceite":"Tipo de aceite: FAAC HP OIL"}', null),
  ('CUU', 'Equipos Electricos', null, 'BOMBA presurizadora', null, null, 'AQUA PAK', 'PRES-AP50-24LM', null, 'Potencia de la Motobomba: 1/2 HP', 'A', null, null, '{"electrica":"Amperaje: 4.7 A. 110v"}', null),
  ('CUU', 'Equipos Electricos', null, 'BOMBA presurizadora', null, null, 'TRUPER', 'Modelo: HIDR-1/2X50', null, '7hp', 'A', null, null, '{}', null),
  ('CUU', 'Equipos Electricos', 'EE-111', 'MOTOR CORTINA 1', null, null, 'MANARAS OMH', 'MANARAS OPH', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('CUU', 'Equipos Electricos', 'EE-112', 'MOTOR CORTINA 2', null, null, 'LiftMaster', 'MH5011UR', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('CUU', 'Equipos Electricos', 'EE-113', 'MOTOR CORTINA 3', null, null, 'LiftMaster', 'MH5011UR', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('CUU', 'Equipos Electricos', 'EE-114', 'MOTOR CORTINA 4', null, null, 'LiftMaster', 'MH5011UR', '2115N6685', '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('CUU', 'Equipos Electricos', 'EE-115', 'MOTOR CORTINA 5', null, null, 'MANARAS OMH', 'MANARAS OPH', null, '1/2 HP', 'A', null, null, '{"electrica":"110V/3.8 AMP"}', null),
  ('GDL', 'Electrico', 'SUB-001', 'Transformador 75 kva — Tipo poste', 'Subestacion', 'Tipo poste', null, null, '7909', '75 kva', 'A', '2012-08-01', '2025-11-13', '{"potencia_kva":"75","voltajes":"23000/220","conexion":"220/127 v","norma":"002/2014","consumo":"19 kw"}', null),
  ('GDL', 'Electrico', 'SUB-002', 'Transformador 225 kva — Tipo Pedestal', 'Subestacion', 'Tipo Pedestal', null, null, '4789', '225 kva', 'A', '2012-02-02', '2025-09-19', '{"potencia_kva":"225","voltajes":"23000/220","conexion":"480/227v","norma":"002/2014","consumo":"75 kw"}', null),
  ('GDL', 'Electrico', 'SUB-003', 'Transformador 300 kva — Tipo seco', 'Subestacion', 'Tipo seco', null, null, null, '300 kva', 'A', null, '2025-09-20', '{"potencia_kva":"300","voltajes":"220/480","conexion":"480/227v","norma":"002/2014","consumo":"1"}', null),
  ('HMO', 'Electrico', 'SUB-004', 'Transformador 50kva — Tipo poste', 'Subestacion', 'Tipo poste', null, null, '575066', '50kva', 'A', null, '2025-10-10', '{"potencia_kva":"50","voltajes":"23000/223","conexion":"220/127 v","norma":"002/2014","consumo":"29 kw"}', null),
  ('MTY', 'Electrico', 'SUB-005', 'Transformador 50 KVA — Tipo poste', 'Subestacion', 'Tipo poste', null, null, null, '50 KVA', 'A', null, '2025-01-17', '{"potencia_kva":"50","voltajes":"23000/224","conexion":"220/127 v","norma":"002/2014","consumo":"8 kw"}', null),
  ('CUU', 'Electrico', 'SUB-006', 'Transformador 45 KVA — Tipo pedestal', 'Subestacion', 'Tipo pedestal', null, null, null, '45 KVA', 'A', null, '2025-10-25', '{"potencia_kva":"45","voltajes":"23000/225","conexion":"220/127 v","norma":"002/2014","consumo":"15 kw"}', null),
  ('CDJ', 'Electrico', 'SUB-007', 'Transformador 35 kva — Tipo poste', 'Subestacion', 'Tipo poste', null, null, null, '35 kva', 'A', null, '2025-10-15', '{"potencia_kva":"35","voltajes":"23000/226","conexion":"220/127 v","norma":"002/2014","consumo":"15 kw"}', null)
) as v(sucursal, categoria, codigo, nombre, ubicacion, tipo, marca, modelo, serie, capacidad, criticidad, finst, ultimo, attrs, notas)
join sucursales s on s.codigo = v.sucursal
left join categorias c on c.nombre = v.categoria;

-- ==================================================================
-- PLANES DE MANTENIMIENTO
-- ==================================================================
insert into planes (categoria_id, nombre, descripcion, frecuencia, servicio, requiere_formato)
select c.id, v.nombre, v.descripcion, v.frecuencia::frecuencia_plan, v.servicio, v.formato
from (values
  ('Electrico', 'Transformadores Electricos', null, 'anual', 'Especializado', true),
  ('Electrico', 'Tableros Electricos', null, 'semestral', 'Equipo ABSA', true),
  ('Electrico', 'Deribados', null, 'semestral', 'Equipo ABSA', true),
  ('Electrico', 'Canalizaciones', null, 'anual', 'Equipo ABSA', true),
  ('Electrico', 'Generador electrico de emergencia', null, 'semestral', 'Especializado', true),
  ('Electrico', 'Transferencia electronica', null, 'semestral', 'Equipo ABSA', true),
  ('Estructural', 'Contenedores de basura — METALICA', 'Lijado y aplicación de pintura de esmalte base solvente color negro (Area de residuos y cuarto electrico. Cantidad: 16 m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Contenedores de basura — TABIQUE', 'Limpieza y aplicación de sellador para tabique expuesto (Area de residuos y cuarto electrico. Cantidad: 36m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — METALICA', 'Lijado y aplicación de pintura de esmalte base solvente color negro (Area de residuos y cuarto electrico. Cantidad: 1.7m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — TABIQUE', 'Limpieza y aplicación de sellador para tabique expuestoincluyendo los escalones (Area de residuos y cuarto electrico. Cantidad: 18 m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — TECHO', 'Limpieza sellado de grietas y aplicación de impermeabilizante y limpieza de bajante (Area de residuos y cuarto electrico. Cantidad: 9 m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — Sistema de tierra fisica', 'Formato de llenado (Area de residuos y cuarto electrico. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — Mntto tablero electrico', 'Formato de llenado (Area de residuos y cuarto electrico. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — Mntto transformador', 'Formato de llenado (Area de residuos y cuarto electrico. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto Electrico — puerta corrediza', 'Mntto prev de estructura metalica, rieles , pintura y cerradura (Area de residuos y cuarto electrico. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — METALICA', 'Lijado y pintura de puertas de metal, jardineras, vigas, soportes, (Caseta, plumas de acceso. Cantidad: 23 m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — TABIQUE', 'Aplicación de sellador en tabique expuesto para retiro de humedad (Caseta, plumas de acceso. Cantidad: 42m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — TECHO', 'Reparacion de filrtraciones resequedad y aplicación de impermeablizante (Caseta, plumas de acceso. Cantidad: 14 m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Luminarias', 'Servicio de mntto prev. En luminarias y apagadores (Caseta, plumas de acceso. Cantidad: 12)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Electrico', 'Servicio de mntto prev. En Tableros electricos, asi como en los derivados(contactos) (Caseta, plumas de acceso. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Pintura', 'Aplicación de resanado y pintura en las areas adecuadas (Caseta, plumas de acceso. Cantidad: 11m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Acabados', 'mntto prev. En Zoclos, percheros, equipo de baño, etc. (Caseta, plumas de acceso. Cantidad: #)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Sanitarios', 'Mantto prev. De sanitarios, valvulas, lavamanos, (Caseta, plumas de acceso. Cantidad: 2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Puertas y accesos', 'Lubricacion de bisagras y chapas (Caseta, plumas de acceso. Cantidad: 5)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Equipo', 'Sillas, escritorios, Microondas, (Caseta, plumas de acceso. Cantidad: #)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Caseta de vigilancia — Cristales', 'Remplazo de cristales blindados dañados y agrietados (Caseta, plumas de acceso. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto electrico 2 — METALICA', 'Lijado y pintura anticorrosiva en puerta de acceso aplicación de pintura esmalte base solvente color negro (cuarto electrico 2. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto electrico 2 — TABIQUE', 'Aplicación de sellador en tabique expuesto para retiro de humedad (cuarto electrico 2. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto electrico 2 — LUMINARIAS', 'Servicio de mntto prev. En luminarias con fotocelda (cuarto electrico 2. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto electrico 2 — ELECTRICO', 'Mantenimiento a ITM principal y derivados (cuarto electrico 2. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto electrico 2 — PUERTAS Y ACCESO', 'Lubricacion de bisagras y chapas (cuarto electrico 2. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Cuarto electrico 2 — EQUIPO', 'transformador electrico 75kva (cuarto electrico 2. Cantidad: 1)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'FACHADA — METALICA', 'Lijado y pintura anticorrosiva en Porton de acceso riel y soportes (Fachada por amapola. Cantidad: 68 M2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'FACHADA — MURO', 'Aplicación de pintura color azul en enjarre de fachada principal (Fachada por amapola. Cantidad: 216 M2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'FACHADA — LUMINARIAS', 'Servicio de mntto prev. En luminarias con fotocelda (Fachada por amapola. Cantidad: 3)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'INTERIOR — JARDINERAS', 'Aplícacion de pintura y resanes en jardineras internas (Fachada por amapola. Cantidad: 72 M2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'INTERIOR — LUMINARIAS', 'Mantenimiento preventivo luminarias (Fachada por amapola. Cantidad: 3)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — METALICA', 'Lijado y pintura anticorrosiva vigas, soportes y refuerzos de metal (Area de mostrador. Cantidad: 136 ML DE VIGA)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — MURO', 'Aplicación de sellador en muro de tabique expuesto para evitar la humedad (Area de mostrador. Cantidad: 222 M2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — LUMINARIAS', 'Servicio de mntto prev. En luminarias (Area de mostrador. Cantidad: 46)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — ELECTRICO', 'Mntto prev. Contactos (Area de mostrador. Cantidad: #)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — PUERTAS DE ACCESO', 'Servicio de mantenimiento a bisagras,cierrapuertas,lubricacion. (Area de mostrador. Cantidad: 5)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — SANITARIOS', 'Servicio de mantenimiento a sistema hidraulico, mangueras, valvulas,monomandos,etc. (Area de mostrador. Cantidad: 2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — PERSIANAS', 'Limpieza/repuestos/remplazo (Area de mostrador. Cantidad: 12)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — ACCESORIOS Y ACABADOS', 'MANTENIMEINTO A SILLAS,ZOCLOS,ETC. (Area de mostrador. Cantidad: #)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'MOSTRADOR — Mobiliario', 'Escritorios, mostradores,etc. (Area de mostrador. Cantidad: #)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Patio de maniobras — Balizado', 'aplicación de pintura (Patio de maniobras. Cantidad: 116 ML x 12 cm)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Patio de maniobras — Jardineras', 'resanado de grietas, aplicación de sellador y pintura (Patio de maniobras. Cantidad: 21 ML x 45 cm)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Patio de maniobras — Andenes', 'limpieza, reapriete de tornilleria, almorol en cubierta, pintura, gomas de amortizacion (Patio de maniobras. Cantidad: 7)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Patio de maniobras — Muros', 'resanado de grietas, aplicación de sellador y pintura (Patio de maniobras. Cantidad: 43m2)', 'anual', 'Equipo ABSA', false),
  ('Estructural', 'Patio de maniobras — Pasillo peatonal', 'sellado de durock (Patio de maniobras. Cantidad: 17 metros cuadrados)', 'anual', 'Equipo ABSA', false)
) as v(categoria, nombre, descripcion, frecuencia, servicio, formato)
left join categorias c on c.nombre = v.categoria;

-- ==================================================================
-- PENDIENTES / REQUERIMIENTOS DETECTADOS
-- ==================================================================
insert into pendientes (sucursal_id, concepto, descripcion, costo_min, costo_max, estatus)
select s.id, v.concepto, v.descripcion, v.cmin, v.cmax, v.estatus
from (values
  ('GDL', 'Transformador electrico', 'Remplazo de transformador dañado', 100000::numeric, 125000::numeric, 'abierto'),
  ('GDL', 'sistema contra incendio', 'Remplazo de tuberia dañada por corrocion', null::numeric, null::numeric, 'cotizando'),
  ('GDL', 'reparacion de aires acondicinados', 'remplazo de equipo/reparacion de tarjetas', 13380::numeric, 13380::numeric, 'abierto'),
  ('GDL', 'Instalacion de aires acondicionados', 'Remplazo de a/a p1c cotizadores', 8600::numeric, 8600::numeric, 'abierto'),
  ('GDL', 'Mantenimiento a equipos de aire acondicionado', 'desgaste fisico de tuberias', 16160::numeric, 16160::numeric, 'abierto'),
  ('GDL', 'Reparacion de goteras', 'filtraciones por grietas', 21000::numeric, 21000::numeric, 'abierto'),
  ('GDL', 'limpieza y sellado de muros', 'retiro de moho', 8320::numeric, 8320::numeric, 'abierto'),
  ('GDL', 'mantenimiento a equipos de bombeo de agua', 'prevencion de fallas', null::numeric, null::numeric, 'abierto'),
  ('GDL', 'retiro de arbol', 'corte del pino', 10748::numeric, 10748::numeric, 'abierto'),
  ('GDL', 'reparacion de daños en estacionamiento', 'reparacion de bacheo por caida del pino', null::numeric, null::numeric, 'abierto'),
  ('GDL', 'reparacion de motores de cortinas', 'cambio de motor/ reparacion de tarjetas', null::numeric, null::numeric, 'abierto'),
  ('CUU', 'Retiro de estructura dañada', 'riesgo de fractura y daños', null::numeric, null::numeric, 'abierto'),
  ('CUU', 'Mantenimiento a tranasformador electrico', 'Mantenimiento preventivo', 25000::numeric, 40000::numeric, 'abierto'),
  ('CUU', 'Reparacion de aires acondicionados', 'mantenimiento correctivo', null::numeric, null::numeric, 'abierto'),
  ('CUU', 'Remplazo de tablero electrico', 'mantenimeinto correctivo', null::numeric, null::numeric, 'abierto'),
  ('HMO', 'Mantenimiento a transformador electrico', null, null::numeric, null::numeric, 'abierto'),
  ('HMO', 'mantenimiento a tableros electricos', null, null::numeric, null::numeric, 'abierto'),
  ('HMO', 'Mantenimiento aires acondicionados', null, null::numeric, null::numeric, 'abierto'),
  ('HMO', 'Mantenimiento a sanitarios', null, null::numeric, null::numeric, 'abierto'),
  ('HMO', 'Mantenimeinto pintura y estructura', null, null::numeric, null::numeric, 'abierto'),
  ('HMO', 'puertas de malla ciclonica', null, null::numeric, null::numeric, 'abierto'),
  ('CDJ', 'Mantenimiento a transformador electrico', null, null::numeric, null::numeric, 'abierto'),
  ('CDJ', 'Mantenimiento a tableros electricos', null, null::numeric, null::numeric, 'abierto'),
  ('CDJ', 'Mantenimiento a equipos de aire acondicionado', null, null::numeric, null::numeric, 'abierto'),
  ('CDJ', 'Daños en pintura', null, null::numeric, null::numeric, 'abierto'),
  ('CDJ', 'Reparacione de piso', null, null::numeric, null::numeric, 'abierto'),
  ('LEO', 'Mantenimiento a cortina metalica', null, null::numeric, null::numeric, 'abierto'),
  ('LEO', 'Sellado e muros por filtraciones', null, null::numeric, null::numeric, 'abierto'),
  ('LEO', 'Pintura e imagen', null, null::numeric, null::numeric, 'abierto')
) as v(codigo, concepto, descripcion, cmin, cmax, estatus)
left join sucursales s on s.codigo = v.codigo;

commit;